---
title: "meeting notes"
output: html_document
---

# Post thanksgiving

1) Plots

I would be fine with no plots. But if we do plots, I think we should not use boxes and arrows. How do you differentiate all the level inferences, or the level from trend inferences, with just boxes and arrows?

Matter of factly say that level and trend on graphs, dynamics with boxes and arrows.

2) Intro

Just highlight vs. problem

3) Mediation

Is that enough? I don't want to talk about this

4) Discussion

Our own opinions?

Notes from talk

1) Intro higher level

Not so referency. We are organizing. Focus on inferences that will never go away. These are patterns that we see, a framework that we have developed and makes the literature easier to parse.

2) Relationships section

TVC model: is the relationship across people consistent over time? It is a correlation across people that is contrained to be the same over time. TVC is more than 1 subject. 

My relationships thing is relationships among time series. Figure 4 is a correlation across time. TVC is a correlation across people that is averaged across time, constrained to be equal across time.

New figure:
Correlation between X and Y on Y axis. Time on x axis. TVC constrians that line to be flat. 

