---

# https://crsh.github.io/papaja_man/index.html

title             : "Thinking About Patterns Over Time"
shorttitle        : "LONGITUDINAL INFERENCES"

author: 
  - name          : "Christopher R. Dishop"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "316 Physics Road, Psychology Building, Room 348, East Lansing, MI, 48823"
    email         : "dishopch@msu.edu"
  - name          : "Michael T. Braun"
    affiliation   : "2"    
  - name          : "Goran Kuljanin"
    affiliation   : "3"
  - name          : "Richard P. DeShon"
    affiliation   : "1"
    
affiliation:
  - id            : "1"
    institution   : "Michigan State University"
  - id            : "2"
    institution   : "University of South Florida"
  - id            : "3"
    institution   : "DePaul University"


author_note: |
  ....

abstract: |
  This paper is about how to think about patterns contained in longitudinal or panel data structures. Organizational scientists recognize that psychological phenomena and processes unfold over time and, to better understand them, organizational researchers increasingly work with longitudinal data and explore inferences within those data structures. Longitudinal inferences may focus on any number of fundamental patterns, including construct trajectories, relationships between constructs, or dynamics. Although the diversity of longitudinal inferences provides a wide foundation for garnering knowledge in any given area, it also makes it difficult for researchers to know the set of inferences they may explore with longitudinal data, which statistical models to use given their question, and how to locate their specific study within the broader set of longitudinal inferences. Studies that collect longitudinal data often only focus on one inference category when they could be asking about many more fundamental patterns and learning additional insights about their process of interest. Moreover, a recent article noted that certain statistical models are inappropriate for inferences about dynamics, so it is important for researchers to know how dynamic inferences differ from other, related ways of thinking about patterns over time such as relationships and trend. In this paper, we develop a framework to describe the variety of between-unit research questions and inferences researchers may explore with longitudinal data -- we demonstrate how to think about these fundamental patterns. 
  
keywords          : "longitudinal inferences, between-unit, growth, trends, dynamics, relationships over time, processes"
#wordcount         : "149"

bibliography      : ["references.bib"]
nocite: '@deshon_multivariate_2012; @xu_deshon_dishop'

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/', echo = TRUE, warning = FALSE, message = FALSE)
```


```{r child = 'lc_intro.Rmd'}
```


```{r child = 'lc_trend.Rmd'}
```

```{r child = 'lc_relationships.Rmd'}
```

```{r child = 'lc_dynamics.Rmd'}
```

```{r child = 'lc_discussion.Rmd'}
```

\newpage

# References
```{r create_references, echo = F}
r_refs(file = "references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
