---
title: "Untitled"
output: pdf_document
---

# Intro References Notes

Longitudinal data help us better understand phenomenon (deeper undersanding of applied issues BEAL; fluctuation and development of experiences is critical to understanding a wide BEAL; longitudinal designs reveal team process BELL; emotion regulation show this with longitudinal methods GRANDEY). 

Phenomon are not static, they are longitudinal and develop over time (sequences of events BEAL; process is not static, change PIT; )

Longitudinal data, models, and tests help us refine our theories  (proposing hypotheses and models refines theories PIT; )

In a way that cross sectional, or static data cannot. (Hulin static data do nothing to reveal how it unfolds).


general calls (grandey)
longitudinal data to help us refine our theories ()


Beal 2015

Beal A: longitudinal data will help us better understand
ESM has the capacity to provide a deeper understanding of numerous applied issues (beal p. 20). 

Beal B: longitudinal data will help us better understand
Capturing not only a snapshot of one's daily experiences but the fluctation and development of those experiences is critical to understanding a wide variety of work-related phenomena (p. 4)

Beal C: you must describe within person processes to truly understand psychological constructs and phenomena
Second, they emphasize that describing these within-person processes is fundamental to understanding not just new questions in our field, but also to providing a stronger frame to support more molar psychological constructs and their relations, such as traits, stable attitudes, or even group-level phenomena (p. 5). 

Beal D: organizational phenomenon are not static. They unfold over time
First, that many, if not most, of the psychological phenomena in which we are interested are not characteristics of people; rather, they are common (or sometimes uncommon) sequences of events and event reactions that play out within each person's stream of experience.

extra
One means of achieving greater recognition of the more immediate, dynamic, and naturalistic contexts that ESM helps explore is to connect this micro-level to higher levels of analysis (p. 18). 
A within person perspective is rising, that encapsulates two ideas: 
  
  Pitariu and Ployhart (2010)

Pitariu A: you must collect longitudinal data and test dynamic models to develop better theory and enhance our understanding of constructs.
on testing dynamic models: "it is essential to building an empirical database that contributes to developing better theory and enhancing our understanding of constructs that unfold over time" (p. 427). 

Pitariu B: dynamic hypotheses and data help refine our theories
Thinking about and proposing dynamic hypotheses "stimulates greater refinement in our existing theories" (p. 411). 

Pitariu C: organizational phenomenon are not static. They unfold over time
"organizational and psychological processes are not static but instead develop, change, and evolve over time" (p. 405).

Bell and Koz (2003)

Bell A: longitudinal data help us better understand
"Longitudinal designs, though less efficient, will be far more revealing of the team phenomeon under investigation" (p. 59). 

Extra
"Temporal concerns are most prominant in the area of team development -- where time is generally viewed as a simple linear progression, but it is vitally relevant to all phases of team processes and performance" (p. 57). 

Grandey & Gabriel (2015)

Grandey A: longitudinal designs help us better understand
a thing about emotion regulation. "Future researchers may be able to show this with longitudinal methods" (p. 329). 


"there is much insight to be gained from micro-level assessments of emotional labor" (p. 328). 

Grandey B: general call for longitudinal designs.
"More attention to the reciprocal and unfolding emotion-emotinoal labor process is needed through momentary assessments or lagged effects" (p. 322). 

Hulin A: have to have longitudinal data to understand a process
quote - comp modeling book
"These snapshots do not allow dynamic causality to unfold across time at its own cadence. Static data often cannot directly answer questions about the models they are supposed to help evaluate" (p. 6). 

To satisfy these calls, a researcher might look to our existing literature for examples of how others understand the patterns they observe in longitudinal data. This literature is not hard to find. 
empricical studies collect more time points
words appear to be growing
esm studies exploding
last 5 studies in jom and jap were longitudinal.


# Other Hook Paragraph sloppy writing



Although there are similarities across this literature, such as repeated meausures and phrases that end with "over time," anyone reading it would be confronted by many points of disconnect. Some researchers use hierarchical linear models (HLM), whereas others employ latent growth curves. Some make inferences about change, whereas others are interested in dynamics or growth. All of these authors are investigating patterns in longitudinal data, but it can be inclear how they fit together across the seemingly unrelated hypotheses, models, and inferences they make. What, then, is a new researcher interested in describing and making inferences with respect to their longitudinal data to do?

Our goal is to organize.



Our literature contains many calls for studies to focus on how things happen over time. 
example
example
example

These calls have resulted in an increasing number of longitudinal studies. 


 
    

Interested in how things happen over time
- longer data sets
- discussions of models with longitudinal data
- various inferences
-but
-ambiguous and disconnected. hard to follow if you are new. we provide an organizing framework. 


Interested in inferences with longitudinal data.
- change, growth
- longer data sets
- diverse models


all empirical
-longer data sets
-models that can handle data over time
-inferences about things that happen over time


- longer data sets
-
- various inferences
-but
-ambiguous and disconnected. hard to follow if you are new. we provide an organizing framework.

# Hook 

The story I'm trying to tell:

* People want us to do stuff with longitudinal data, but this literature is messy and confusing. We could use some organization.

opening one
Interested in how things happen over time
greater emphasis in theory
greater number of time points among empirical studies
greater use of models that require longitudinal data

We --organizational researchers-- are increasingly interested in how things happen over time. Emergence, growth, change, dynamics, and process explanations are becoming explicit in organizational theory. Empirical tests of our theories now commonly collect longitudinal data sets with a growing number of time points. New statistical techniques to support inferences with these longitudinal data structures emerge every year. Computational modelers have made their role for refining process knowledge clear and their frequency appears to be growing. Across these developments, however, researchers present seemingly unrelated hypotheses and employ diverse statistical approaches – which impedes any unity about how to demonstrate and support a process inference.




opening two
there is now a large literature on inferences with longitudinal data.
greater number of longitudinal studies with growing number of time points
studies use models that require longitudinal data
make inferences about patterns that happen over time
write theory about what happens over time

opening three
we increasingly interested in how things happen over time. 
greater role in theory
explicit calls for research in this area

this results in empirical studies with a growing number of time points
models that require longitudinal data
inferences about the observed patterns in longitudianl data

but it is confusing. 


opening four
many calls for greater emphasis on how things happen over time

if a researcher was interested, they would then look to the literature on longitudinal investigations. They would find many. Greater use of longitudianl designs with a growing number of time points

although these studies have similarities, repeated measures and phrases that entail "over time," they use different models, make seeingly unrelated predictions and inferences, etc. etc. etc. What is a researcher to do?

we want to provide some clarity. 

# Hook

The story I am trying to tell:

* People want us to do stuff with longitudinal data, to make inferences over time. But this literature is messy and confusing. We could use some organization.

To satisfy these calls, we might want to conduct our own longitudinal investigation and look to the literature for help. 






Increasingly interested in how things happen over time
results in a literature where there are many similarities, such as their repeated measures and use of phrases with 'over time.' 

We – organizational researchers – are increasingly interested in how things happen over time. 
- empirical studies collect more time points
- greater use of models that require longitudinal data
- greater focus in theory
- greater number of inferences

When you look at this literature there are a number of similarities. 
-stuff about the increasing interest of how things happen over time




Empirical studies, for example, commonly employ longitudinal designs and collect data over a growing number of time points. Two decades ago the typical data structure was..., whereas today we (Or, the last five pubs in JOM & JAP were all longitudinal) ... Moreover, researchers appear to be placing greater emphasis on modeling techniques that can handle longitudinal data. It is now common to use hierarchical linear (or random-coefficient or multi-level) modeling to capture relationships over time, and a growing number of studies now use latent growth curve models (cites). Finally, researchers collect and apply models to these data to ultimately form inferences, such as change or growth, about the patterns they observe.



Among these developments, researchers present seemingly unrelated hypotheses, diverse statistical models, and tend to focus on one inference, or a set of inferences, related to one dimension at play in longitudinal data (e.g., growth). 

BUT IF YOU WERE TO LOOK AT THESE STUDIES YOU WOULD FIND UNRELATED INFERENCES. RELATIONSHIPS, CHANGE, GROWTH. THESE ARE ALL "OVER TIME," BUT IT IS UNCLEAR HOW THEY ARE ORGANIZED OR RELATED. 

interested in how things happen over time. 
-longitudinal data sets

Common
-models
-over time

Look at these studies, you find common areas -- repeated measures, descriptions that use the phrase "over time" -- but many areas that appear unrelated. Different inferences, different models, different hypotheses. 

either HLM or growth models -- but 





using models there appears to be a greater use of staistical models 

researchers using modeling strategies to handle longitudinal data. 

Researchers then apply These data structures then draw greater use of statistical models that are amenable to longitudinal designs. Hiarchical linear modeling (or random-coefficient, multi-level) 

Moreover, we also see greater use of statistical models  researchers apply models that can handle longitudinal data

our statistical literature appears to take interest in emphasizes shows a greater emphasis on 

statistical literature on the models that can be applied to these data sets. 

new models and statistical techniques to apply to these data emerge every year. Some examples include ... Finally, there are a variety of inferences researchers make about the relationships they observe with longitudinal data, inferences 

Empirical studies commonly employ longitudinal designs and collect data over a growing number of time points, new models and statistical techniques to apply to these data emerge every year, and there are a variety of inferences researchers make about the relationships they observe with longitudinald data. 

Emergence, growth, change, dynamics, and process explanations are becoming explicit in organizational theory. Empirical tests of our theories now commonly collect longitudinal data sets with a growing number of time points. New statistical models  and  New statistical techniques to support inferences with these longitudinal data structures emerge every year. Computational modelers have made their role for refining process knowledge clear and their frequency appears to be growing. Across these developments, however, researchers present seemingly unrelated hypotheses and employ diverse statistical approaches – which impedes any unity about how to demonstrate and support a process inference.

Researchers that study process are therefore in a similar state to those that were interested in multilevel phenomena two decades ago. Then, we debated how to measure multilevel constructs, justify aggregation, and analyze multilevel models (Klein & Kozlowski, 2000), and our research advanced only after developing consensus. Now, we conceptualize and model different aspects of process -- such as change, growth, or dynamics -- without a shared understanding of the diverse approaches and pitfalls of each. We need to clearly understand how researchers’ approach and justify the variety of inferences they make about the processes in longitudinal data – and the drawbacks of each – to avoid inferential errors and to develop the process knowledge so many authors call for (zillion cites). 

Our goal is to explain these various approaches and provide a guide for researchers who want to study process. Researchers tend to focus on an inference, or set of inferences, related to one dimension at play in longitudinal data (e.g., growth), and this results in seemingly unrelated hypotheses and model applications across research streams. We unpack the core inference underlying each, discuss their differences, provide examples and direct readers to possible statistical models, and show how they can be used to cumulatively understand process.
