---
output: pdf_document
---

Organizational phenomena unfold over time. They are processes that develop, change, and evolve [@pitariu_explaining_2010] that create a sequence of events within a person's stream of experience [@beal_esm_2015]. Moreover, organizations are systems with many connected parts, and systems are inherently dynamic. Studying these systems and processes, therefore, requires that we attend not to static snapshots of behavior [@ilgen_computational_2000], but to variables and relationships as they move through time; doing so puts us in a better position to capture the sequence, understand it, and can lead to new and interesting insights [@kozlowski_work_2003].

**Option A...It's hard for newcomers**

Although our field is increasingly interested in exploring patterns in longitudinal data, process-oriented methods are still relatively new to our field and newcomers without much longitudinal modeling training may be unfamiliar with the variety of questions they can ask. Consider a few recent longitudinal studies that all pose different questions. @jones_baby_2016 ask if the trajectories among certain variables increase or decrease over time. @johnson_good_2014 study how changes in one variable relate to changes in another across time. @hardy_interrelationships_2018 inquire about dynamic relationships, where prior values on one variable predict subsequent values on another, and this second variable then goes back to predict the first at a later point in time. Finally, @meier_reciprocal_2013 examine how effect sizes change when they vary the time lag between their independent and dependent variable. 

There are then complex statistical models that researchers evoke to examine their questions. @meier_reciprocal_2013 present a sequence of path models that test increasingly longer time lags. @hardy_interrelationships_2018 and @jones_baby_2016 employ bivariate cross-lagged latent growth curves, an approach similar to the latent change model used by @ritter_understanding_2016. We also find complex hierarchical linear models in many event-sampling studies [e.g., @koopman_integrating_2016; @rosen_who_2016]. Again, researchers without much longitudinal modeling training may not know when to apply each model -- or which model is appropriate for a given question.

Finally, the spine of an investigation is to interpret the model and make an inference regarding the original question. @jones_baby_2016 infer negative slopes for concealing behaviors and positive slopes for revealing behaviors. @johnson_good_2014 state that justice behaviors fluctuate day to day and predict changes in depletion. @hardy_interrelationships_2018 find support for dynamic relationships between self-efficacy, metacognition, and exploratory behaviors. Finally, @meier_reciprocal_2013 suggest that the effects of work stressors on counterproductive work behaviors are not substantially different across different time lags.

In this paper we discuss the common inferences that researchers in our field make when they apply a model to longitudinal data. As should be clear to anyone reading our literature, there is great excitement for the utility of longitudinal studies; they can pose interesting questions and discover patterns that would otherwise be impossible to capture in a static investigation. We bring attention to the span of questions available so that researchers can fully appreciate and take advantage of their data. Although the inferences concern trajectories or relationships over time, their small differences have large implications for what we take away from them -- what we ultimately conclude. Moreover, there are many inferences, many models, and different models can be used to understand or explore the same inference. In this paper, we provide readers with potential models for each inference so that they can be sure that the model they evoke is appropriate for the research question that they are interested in. In summary, this paper exposes researchers to the span of inferences they may investigate when they collect longitudinal data, links those inferences to models, and parses some of the modeling literature that may be difficult to consume for researchers with only graduate level training in statistics.

**Option B...Just highlighting the literature**

There are many interesting questions researchers can explore with longitudinal data. Consider a few recent longitudinal studies that all pose different questions.  @jones_baby_2016 ask if the trajectories among certain variables increase or decrease over time. @johnson_good_2014 study how changes in one variable relate to changes in another across time. @hardy_interrelationships_2018 inquire about dynamic relationships, where prior values on one variable predict subsequent values on another, and this second variable then goes back to predict the first at a later point in time. Finally, @meier_reciprocal_2013 examine how effect sizes change when they vary the time lag between their independent and dependent variable.   

There are then complex statistical models that researchers evoke to examine their questions. @meier_reciprocal_2013 present a sequence of path models that test increasingly longer time lags. @hardy_interrelationships_2018 and @jones_baby_2016 employ bivariate cross-lagged latent growth curves, an approach similar to the latent change model used by @ritter_understanding_2016. We also find complex hierarchical linear models in many event-sampling studies [e.g., @koopman_integrating_2016; @rosen_who_2016].

Finally, the spine of an investigation is to interpret the model and make an inference regarding the original question. @jones_baby_2016 infer negative slopes for concealing behaviors and positive slopes for revealing behaviors. @johnson_good_2014 state that justice behaviors fluctuate day to day and predict changes in depletion. @hardy_interrelationships_2018 find support for dynamic relationships between self-efficacy, metacognition, and exploratory behaviors. Finally, @meier_reciprocal_2013 suggest that the effects of work stressors on counterproductive work behaviors are not substantially different across different time lags.

In this paper we discuss the common inferences that researchers in our field make when they apply a model to longitudinal data. As should be clear to anyone reading our literature, there is great excitement for the utility of longitudinal studies; they can pose interesting questions and discover patterns that would otherwise be impossible to capture in a static investigation. We bring attention to the span of questions available so that researchers can fully appreciate and take advantage of their data. Although the inferences concern trajectories or relationships over time, their small differences have large implications for what we take away from them -- what we ultimately conclude. Moreover, there are many inferences, many models, and different models can be used to understand or explore the same inference. In this paper, we provide readers with potential models for each inference so that they can be sure that the model they evoke is appropriate for the research question that they are interested in. In summary, this paper exposes researchers to the span of inferences they may investigate when they collect longitudinal data, links those inferences to models, and parses some of the modeling literature that may be difficult to consume for researchers with only graduate level training in statistics. 

# Longitudinal Definitions

This paper is exclusively devoted to the inferences we make with repeated observations, so we begin by identifying a few labels and definitions. Authors typically identify a "longitudinal" study by contrasting either a) research designs or b) data structures. Longitudinal *research* is different from cross-sectional research because longitudinal designs entail three or more repeated observations [@ployhart_longitudinal_2010]. We therefore emphasize differences on the number of observations when we distinguish longitudinal from other types of research. Longitudinal *data* are repeated observations on several units (i.e., $N$ or $i$ > 1), whereas panel data are observations of one unit over time -- a distinction that focuses on the amount of people in our study (given repeated measures). Most organizational studies collect data on more than one unit, therefore our discussion below focuses on longitudinal research with longitudinal data, or designs with $N$ > 1, $t$ >= 3, and the same construct(s) measured on each $i$ at each $t$. 

# Framework

We use three inference categories to partition our discussion, including level, trend, and dynamics. Each of these are broad categories, and they will all have their own sub-inferences and models. Our writing style will be the same throughout each section, where we first discuss the category itself and then sequentially walk through the inferences. During that sequence, we will pose questions to orient the reader as to what the inference captures, unpack graphs and figures, and then close with a table that provides example hypotheses that align with each inference. The figures we use in the level and trend sections are graphs that show what the inferences look like in data -- we feel that graphing the inferences with respect to data is more informative than your usual box and arrow diagram. There is a caveat, however, that we want to make sure everyone is aware of. Data are always messy. It is rare to find data where the inferences expose themselves simply by plotting -- although it is certainly possible. We are using these "data plots" to clearly convey what the inferences mean, but please be aware that field data will always be messy. When we discuss dynamics section we then use box and arrow diagrams because they better convey the ideas in that section. 

Finally, we end each inference section by pointing researchers to respective statistical models. Although we direct researchers to models, our paper is not about statistical modeling only -- it is about inferences -- and researchers therefore need to be sure that they appreciate all of the nuance before applying a recommended model. There are many complex statistical issues that arise with longitudinal modeling -- like stationarity -- and the models differ in how they handle these issues, the assumptions they make, and the data format they require. There are plenty of great references on each model, what we are doing here is guiding researchers to those references based on the underlying inferences that interest them.
